base_url = "https://araruna.science"

title = "Prof. Arthur Araruna"
description = "Informações profissionais sobre o Prof. Arthur Araruna do Campus de Quixadá da Universidade Federal do Ceará."

default_language = "pt"

minify_html = true

build_search_index = true

taxonomies = [
    { name = "area" },
    { name = "academic_level" },
    { name = "artifact" },
    { name = "grant_agency" },
]

[markdown]
smart_punctuation = true

external_links_target_blank = true
external_links_no_follow = true

[link_checker]
external_level = "warn"

[languages.en]
title = "Prof. Arthur Araruna"
description = "Informations about Prof. Arthur Araruna's professional activity, from Quixadá's Campus at the Federal University of Ceará."

[extra]
# Based on what is found on https://github.com/getzola/even/
katex_enable = true
katex_auto_render = false

# Kodama Theme configs
email = "ararunaufc@gmail.com"
avatar = "static/img/Eu.jpg"
favicon = "static/img/Eu.jpg"

menu_items = []

[translations]
lang_name = "Português (Brasileiro)"

biography = "Biografia"
interests = "Interesses"
education = "Formação Acadêmica"

[languages.en.translations]
lang_name = "English"

biography = "Biography"
interests = "Interests"
education = "Education"
